<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html><html><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Seller Studio · NexoraMart</title><link rel="stylesheet" href="<%=request.getContextPath()%>/css/style.css">
</head><body class="seller-dashboard-page">
<header class="nav seller-pro-nav seller-max-nav"><b>NEXORA<span>MART</span></b><div class="seller-nav-links"><a href="<%=request.getContextPath()%>/seller/dashboard">Command Center</a><a class="active" href="<%=request.getContextPath()%>/seller/products">Products</a><a href="<%=request.getContextPath()%>/seller/orders">Orders</a><a href="<%=request.getContextPath()%>/marketplace">Storefront</a></div><div class="nav-right"><a class="button small" href="<%=request.getContextPath()%>/logout">Logout</a></div></header>
<main class="seller-max-page seller-products-page">
  <section class="seller-page-title-row"><div><span class="seller-kicker">SELLER STUDIO</span><h1>Build your catalog.</h1><p>Launch polished listings with complete specifications, stock and product imagery.</p></div><a class="button ghost" href="<%=request.getContextPath()%>/seller/dashboard">← Dashboard</a></section>
  <% if(request.getAttribute("error")!=null){ %><div class="alert"><%=request.getAttribute("error")%></div><% } %>
  <section class="seller-form-shell">
    <div class="seller-form-intro"><span class="seller-kicker">NEW LISTING</span><h2>Add a product</h2><p>Complete the details once. Your storefront and product detail page will reuse the same information.</p><div class="seller-form-badges"><span>🖼️ 3 image slots</span><span>📦 stock aware</span><span>⚡ instant publish</span></div></div>
    <form method="post" class="seller-product-form"><input type="hidden" name="action" value="add">
      <div class="seller-form-section"><h3>1. Identity</h3><div class="seller-form-grid"><label>Product name<input name="name" placeholder="e.g. Nexora Phone Pro" required></label><label>Brand<input name="brand" placeholder="Brand name"></label><label>Model<input name="model" placeholder="Model / series"></label><label>Category<select name="category"><option>Mobile</option><option>Audio</option><option>Accessories</option><option>Laptop</option><option>Stationery</option></select></label></div><label>Product description<textarea name="description" placeholder="Tell buyers what makes this product useful on campus..."></textarea></label></div>
      <div class="seller-form-section"><h3>2. Specifications</h3><div class="seller-form-grid"><label>RAM<input name="ram" placeholder="e.g. 8 GB"></label><label>Storage<input name="storage" placeholder="e.g. 256 GB"></label><label>Display<input name="displaySize" placeholder="e.g. 6.7 inch"></label><label>Camera<input name="camera" placeholder="e.g. 50 MP"></label><label>Battery<input name="battery" placeholder="e.g. 5000 mAh"></label><label>Price (₹)<input name="price" type="number" min="0" step="0.01" placeholder="0.00" required></label><label>Stock quantity<input name="stockQty" type="number" min="0" placeholder="0" required></label></div></div>
      <div class="seller-form-section"><h3>3. Product images</h3><p class="seller-form-help">Use local paths such as <code>/images/nexora-x1-1.svg</code> or a trusted image URL.</p><div class="seller-form-grid"><label>Image 1<input name="imageUrl1" placeholder="Main image path / URL"></label><label>Image 2<input name="imageUrl2" placeholder="Angle / alternate image"></label><label>Image 3<input name="imageUrl3" placeholder="Angle / alternate image"></label></div></div>
      <div class="seller-form-actions"><button class="button" type="submit">Publish Product →</button><span>Required fields are marked by the browser.</span></div>
    </form>
  </section>

  <section class="seller-list-section"><div class="seller-page-title-row compact"><div><span class="seller-kicker">MY CATALOG</span><h2>Your listings</h2></div><span class="seller-list-count"><c:out value="${products.size()}"/> listing(s)</span></div>
    <div class="seller-catalog-grid">
      <c:forEach var="p" items="${products}">
        <article class="seller-catalog-card">
          <div class="seller-catalog-head"><div class="seller-catalog-image"><c:choose><c:when test="${not empty p.imageUrl1}"><img src="${p.imageUrl1}" alt="${p.name}"></c:when><c:otherwise>📦</c:otherwise></c:choose></div><div class="seller-catalog-title"><span class="seller-catalog-category"><c:out value="${p.category}"/></span><h3><c:out value="${p.name}"/></h3><small><c:out value="${p.brand}"/> · <c:out value="${p.model}"/></small></div><span class="seller-stock-chip ${p.stockQty == 0 ? 'danger' : p.stockQty <= 5 ? 'warn' : 'good'}"><c:choose><c:when test="${p.stockQty == 0}">Out of stock</c:when><c:otherwise>${p.stockQty} in stock</c:otherwise></c:choose></span></div>
          <div class="seller-catalog-specs"><span>RAM <b><c:out value="${p.ram}"/></b></span><span>Storage <b><c:out value="${p.storage}"/></b></span><span>Display <b><c:out value="${p.displaySize}"/></b></span><span>₹ <b><c:out value="${p.price}"/></b></span></div>
          <div class="seller-catalog-actions"><a class="button ghost" href="<%=request.getContextPath()%>/product/details?id=${p.id}">View</a><form method="post"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="${p.id}"><button class="seller-danger-btn" type="submit" onclick="return confirm('Delete this product?')">Delete</button></form><details><summary>Edit</summary><form method="post" class="seller-inline-edit"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="${p.id}"><label>Name<input name="name" value="${p.name}" required></label><div class="seller-form-grid"><label>Brand<input name="brand" value="${p.brand}"></label><label>Model<input name="model" value="${p.model}"></label><label>Price<input name="price" type="number" step="0.01" min="0" value="${p.price}" required></label><label>Stock<input name="stockQty" type="number" min="0" value="${p.stockQty}" required></label><label>RAM<input name="ram" value="${p.ram}"></label><label>Storage<input name="storage" value="${p.storage}"></label><label>Display<input name="displaySize" value="${p.displaySize}"></label><label>Camera<input name="camera" value="${p.camera}"></label><label>Battery<input name="battery" value="${p.battery}"></label><label>Category<select name="category"><option ${p.category=='Mobile'?'selected':''}>Mobile</option><option ${p.category=='Audio'?'selected':''}>Audio</option><option ${p.category=='Accessories'?'selected':''}>Accessories</option><option ${p.category=='Laptop'?'selected':''}>Laptop</option><option ${p.category=='Stationery'?'selected':''}>Stationery</option></select></label></div><label>Description<textarea name="description">${p.description}</textarea></label><div class="seller-form-grid"><label>Image 1<input name="imageUrl1" value="${p.imageUrl1}"></label><label>Image 2<input name="imageUrl2" value="${p.imageUrl2}"></label><label>Image 3<input name="imageUrl3" value="${p.imageUrl3}"></label></div><button class="button" type="submit">Save Changes</button></form></details></div>
        </article>
      </c:forEach>
    </div>
  </section>
</main><script src="<%=request.getContextPath()%>/js/theme.js"></script></body></html>
