package com.jayaseelan.nexoramart.dao;
import com.jayaseelan.nexoramart.model.Product; import javax.sql.DataSource; import java.sql.*; import java.util.*;
public class JdbcProductDAO implements ProductDAO{
 private final DataSource ds; public JdbcProductDAO(DataSource d){ds=d;}
 private Product map(ResultSet r)throws SQLException{Product p=new Product();p.setId(r.getLong("id"));p.setSellerId(r.getLong("seller_id"));p.setSellerName(r.getString("seller_name"));p.setName(r.getString("name"));p.setBrand(r.getString("brand"));p.setModel(r.getString("model"));p.setDescription(r.getString("description"));p.setPrice(r.getBigDecimal("price"));p.setStockQty(r.getInt("stock_qty"));p.setCategory(r.getString("category"));p.setRam(r.getString("ram"));p.setStorage(r.getString("storage"));p.setDisplaySize(r.getString("display_size"));p.setCamera(r.getString("camera"));p.setBattery(r.getString("battery"));p.setImageUrl1(r.getString("image_url_1"));p.setImageUrl2(r.getString("image_url_2"));p.setImageUrl3(r.getString("image_url_3"));return p;}
 private String select(){return "SELECT p.*,COALESCE(u.name,'Campus Seller') AS seller_name FROM products p LEFT JOIN users u ON u.id=p.seller_id";}
 public void create(Product p)throws SQLException{String q="INSERT INTO products(seller_id,name,brand,model,description,price,stock_qty,category,ram,storage,display_size,camera,battery,image_url_1,image_url_2,image_url_3) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(q)){s.setLong(1,p.getSellerId());s.setString(2,p.getName());s.setString(3,p.getBrand());s.setString(4,p.getModel());s.setString(5,p.getDescription());s.setBigDecimal(6,p.getPrice());s.setInt(7,p.getStockQty());s.setString(8,p.getCategory());s.setString(9,p.getRam());s.setString(10,p.getStorage());s.setString(11,p.getDisplaySize());s.setString(12,p.getCamera());s.setString(13,p.getBattery());s.setString(14,p.getImageUrl1());s.setString(15,p.getImageUrl2());s.setString(16,p.getImageUrl3());s.executeUpdate();}}
 public List<Product> findAll(String q,String cat)throws SQLException{StringBuilder b=new StringBuilder(select()).append(" WHERE p.active=TRUE AND p.stock_qty>0");List<Object>a=new ArrayList<>();if(q!=null&&!q.isBlank()){b.append(" AND (LOWER(p.name) LIKE ? OR LOWER(COALESCE(p.brand,'')) LIKE ? OR LOWER(COALESCE(p.model,'')) LIKE ? OR LOWER(COALESCE(p.category,'')) LIKE ? OR LOWER(COALESCE(p.ram,'')) LIKE ? OR LOWER(COALESCE(p.storage,'')) LIKE ?)");String l="%"+q.trim().toLowerCase()+"%";for(int i=0;i<6;i++)a.add(l);}if(cat!=null&&!cat.isBlank()){b.append(" AND LOWER(p.category)=LOWER(?)");a.add(cat.trim());}b.append(" ORDER BY p.created_at DESC,p.id DESC");return query(b.toString(),a);}
 public List<Product> findBySeller(long id)throws SQLException{return query(select()+" WHERE p.seller_id=? ORDER BY p.created_at DESC,p.id DESC",List.of(id));}
 public Product findById(long id)throws SQLException{List<Product> x=query(select()+" WHERE p.id=? AND p.active=TRUE",List.of(id));return x.isEmpty()?null:x.get(0);}
 private List<Product> query(String q,List<?> a)throws SQLException{List<Product> out=new ArrayList<>();try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(q)){for(int i=0;i<a.size();i++)s.setObject(i+1,a.get(i));try(ResultSet r=s.executeQuery()){while(r.next())out.add(map(r));}}return out;}
 public void update(Product p,long sid)throws SQLException{String q="UPDATE products SET name=?,brand=?,model=?,description=?,price=?,stock_qty=?,category=?,ram=?,storage=?,display_size=?,camera=?,battery=?,image_url_1=?,image_url_2=?,image_url_3=? WHERE id=? AND seller_id=?";try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(q)){s.setString(1,p.getName());s.setString(2,p.getBrand());s.setString(3,p.getModel());s.setString(4,p.getDescription());s.setBigDecimal(5,p.getPrice());s.setInt(6,p.getStockQty());s.setString(7,p.getCategory());s.setString(8,p.getRam());s.setString(9,p.getStorage());s.setString(10,p.getDisplaySize());s.setString(11,p.getCamera());s.setString(12,p.getBattery());s.setString(13,p.getImageUrl1());s.setString(14,p.getImageUrl2());s.setString(15,p.getImageUrl3());s.setLong(16,p.getId());s.setLong(17,sid);s.executeUpdate();}}
 public void delete(long id,long sid)throws SQLException{try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement("DELETE FROM products WHERE id=? AND seller_id=?")){s.setLong(1,id);s.setLong(2,sid);s.executeUpdate();}}
}
