<%@ page contentType="text/html;charset=UTF-8" %>
<%@ page import="java.util.List,java.text.SimpleDateFormat,com.jayaseelan.nexoramart.model.Order,com.jayaseelan.nexoramart.model.OrderItem" %>
<% List<Order> orders=(List<Order>)request.getAttribute("orders"); SimpleDateFormat fmt=new SimpleDateFormat("dd MMM yyyy, hh:mm a"); %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Seller Orders · NexoraMart</title><link rel="stylesheet" href="<%=request.getContextPath()%>/css/style.css"></head>
<body class="seller-dashboard-page"><header class="nav seller-pro-nav seller-max-nav"><b>NEXORA<span>MART</span></b><div class="seller-nav-links"><a href="<%=request.getContextPath()%>/seller/dashboard">Command Center</a><a href="<%=request.getContextPath()%>/seller/products">Products</a><a class="active" href="<%=request.getContextPath()%>/seller/orders">Orders</a><a href="<%=request.getContextPath()%>/marketplace">Storefront</a></div><div class="nav-right"><a class="button small" href="<%=request.getContextPath()%>/logout">Logout</a></div></header>
<main class="seller-max-page"><section class="seller-page-title-row"><div><span class="seller-kicker">ORDER OPERATIONS</span><h1>Process customer orders.</h1><p>Move every order forward with a clear delivery workflow.</p></div><a class="button ghost" href="<%=request.getContextPath()%>/seller/dashboard">← Command Center</a></section>
<% if("true".equals(request.getParameter("updated"))){ %><div class="success">Order status updated successfully.</div><% } else if("false".equals(request.getParameter("updated"))){ %><div class="alert">That status transition is not allowed for this order.</div><% } %>
<% if(orders==null||orders.isEmpty()){ %><section class="seller-empty-large"><div>🧾</div><h2>No customer orders yet</h2><p>New orders containing your products will appear here.</p></section><% } else { for(Order order:orders){ %>
<section class="seller-order-card">
  <div class="seller-order-card-head"><div><span class="seller-order-ref"><%=order.getOrderRef()%></span><h2><%=order.getBuyerName()%></h2><small><%=fmt.format(order.getCreatedAt())%></small></div><span class="status-pill status-<%=order.getStatus().toLowerCase()%>"><%=order.getStatus()%></span></div>
  <div class="seller-steps"><span class="<%=order.getStatus().equals("PENDING")||order.getStatus().equals("CONFIRMED")||order.getStatus().equals("SHIPPED")||order.getStatus().equals("DELIVERED")?"done":""%>">1 <b>Pending</b></span><i></i><span class="<%=order.getStatus().equals("CONFIRMED")||order.getStatus().equals("SHIPPED")||order.getStatus().equals("DELIVERED")?"done":""%>">2 <b>Confirmed</b></span><i></i><span class="<%=order.getStatus().equals("SHIPPED")||order.getStatus().equals("DELIVERED")?"done":""%>">3 <b>Shipped</b></span><i></i><span class="<%=order.getStatus().equals("DELIVERED")?"done":""%>">4 <b>Delivered</b></span></div>
  <div class="seller-order-items"><% for(OrderItem item:order.getItems()){ %><div><span><%=item.getProductName()%> <b>× <%=item.getQuantity()%></b></span><strong>₹<%=item.getSubtotal()%></strong></div><% } %></div>
  <div class="seller-order-footer"><div><small>Order total</small><b>₹<%=order.getTotalAmount()%></b></div><form method="post" action="<%=request.getContextPath()%>/seller/orders" class="seller-status-form"><input type="hidden" name="orderId" value="<%=order.getId()%>"><label>Next status<select name="status"><% if("PENDING".equals(order.getStatus())){ %><option value="CONFIRMED">Confirm Order</option><% } else if("CONFIRMED".equals(order.getStatus())){ %><option value="SHIPPED">Mark Shipped</option><% } else if("SHIPPED".equals(order.getStatus())){ %><option value="DELIVERED">Mark Delivered</option><% } else { %><option value=""><%=order.getStatus()%></option><% } %></select></label><button class="button" type="submit" <%= ("DELIVERED".equals(order.getStatus())||"CANCELLED".equals(order.getStatus())) ? "disabled" : "" %>>Update Status</button></form></div>
</section><% }} %></main><script src="<%=request.getContextPath()%>/js/theme.js"></script></body></html>
